language: objective-c
osx_image: xcode8.3
install:
  - brew update && brew uninstall --force carthage && brew install carthage
  - gem install xcpretty
before_script: carthage bootstrap --platform iphoneos
script: rake test:all
